num_classes: 80

in_channels: 3

# [depth, width, max_channels]
scale: [0.33, 0.25, 1024]

# [module, from, repeats, args]
# [Conv, from, N/A, [c_out, k, s]]
# [C2f, from, repeats, [c_out, shortcut]]
# [SPPF, from, N/A, [c_out, kernel_size]]
# [nn.Upsample, from, N/A, [None, scale_factor, mode]]
# [DetectionHead, from, N/A, [num_classes]]

backbone:
  - [Conv, -1, null, [64, 3, 2]]    # 0 (640,640,3) -> (320,320,64)
  - [Conv, -1, null, [128, 3, 2]]   # 1 (320,320,64) -> (160,160,128)
  - [C2f,  -1, 3, [128, True]]      # 2 (160,160,128) -> (160,160,128)
  - [Conv, -1, null, [256, 3, 2]]   # 3 (160,160,128) -> (80,80,256)
  - [C2f,  -1, 6, [256, True]]      # 4 (80,80,256) -> (80,80,256)
  - [Conv, -1, null, [512, 3, 2]]   # 5 (80,80,256) -> (40,40,512)
  - [C2f,  -1, 6, [512, True]]      # 6 (40,40,512) -> (40,40,512)
  - [Conv, -1, null, [1024, 3, 2]]  # 7 (40,40,512) -> (20,20,1024)
  - [C2f,  -1, 3, [1024, False]]    # 8 (20,20,1024) -> (20,20,1024)
  - [SPPF, -1, null, [1024, 5]]     # 9 (20,20,1024) -> (20,20,1024)

head:
  - [nn.Upsample, -1, null, [None, 2, 'nearest']]  # 10 (20,20,1024) -> (40,40,1024)
  - [C2f, [-1, 6], 3, [512, False]]                # 11 (40,40,512+1024) -> (40,40,512)

  # P3
  - [nn.Upsample, -1, null, [None, 2, 'nearest']]  # 12 (40,40,512) -> (80,80,512)
  - [C2f, [-1, 4], 3, [256, False]]                # 13 (80,80,256+512) -> (80,80,256)

  # P4
  - [Conv, -1, null, [256, 3, 2]]                  # 14 (80,80,256) -> (40,40,256)
  - [C2f, [-1, 11], 3, [512, False]]               # 15 (40,40,512+256) -> (40,40,512)

  # P5
  - [Conv, -1, null, [512, 3, 2]]                  # 16 (40,40,512) -> (20,20,512)
  - [C2f, [-1, 9], 3, [1024, False]]               # 17 (20,20,1024+512) -> (20,20,1024)

  - [DetectionHead, [13, 15, 17], null, [80]]      # 18 (h,w,c) -> (h,w,nc+4*reg_max)